### ISSUE TITLE
Talk Proposal

### ISSUE THREAD

**Issue by iadknet** [PDXNode/pdxnode#73]
We have developed a lightweight node app that allows us to develop our frontend components as microservices, register them with consul, and use traefik (https://github.com/containous/traefik) as a routing gateway. 

If there is interest, I'd like to give a presentation on this project.

**Comment by aulvi** [comment]
I like it! How much time would you like to present, and when would you like to give this presentation? Thanks!

**Comment by iadknet** [comment]
I think 30 minutes should be sufficient. I could be prepared anytime after this week (I don't think I could pull it together for this week's meetup).

**Comment by aulvi** [comment]
Sounds great. Would next month work for you?

**Comment by iadknet** [comment]
Next month would be great!

**Comment by aulvi** [comment]
Awesome, I'll pencil you in and follow up later in the month. Looking forward to seeing your presentation!

**Comment by iadknet** [comment]
Hi there!  I just wanted to confirm that I am still on for the presentation this week.

**Comment by warbrett** [comment]
Not only are you confirmed, you can even go first if you want!

**Comment by iadknet** [comment]
Works for me!

**Comment by aulvi** [comment]
Thanks again for speaking!
