### ISSUE TITLE
Talk Proposal: How JavaScript Evolves

### ISSUE THREAD

**Issue by FaustDeGoethe** [PDXNode/pdxnode#74]
In this talk we'll discuss the history of the [JavaScript specification](https://tc39.github.io/ecma262/) and how implementers and developers make use of it to improve the JavaScript language year over year.

As a case study I'll go over the specification changes I've proposed for `Date.parse` which have recently been given a "stage-one" status. https://github.com/mrrrgn/proposal-date-time-string-format

By the end of the talk JavaScript developers should have a good idea of how they can track upcoming changes to the language and how they might get involved in shaping its future.

Estimated time: 40 minutes.

**Comment by aulvi** [comment]
Sounds great, when would you like to present and how much time would you like? Thanks!

**Comment by bcomnes** [comment]
LGTM!

**Comment by mrrrgn** [comment]
Yay, thanks! I won't be able to speak during September, but would be happy to talk anytime in October or later.

**Comment by mrrrgn** [comment]
Whoops, forgot to add how much time. I'd say 40 minutes is plenty. It could be 30 if that would be more convenient.

**Comment by aulvi** [comment]
We don't have a "max" presentation length, 40 minutes is totally fine. I'll pencil you in for October and will follow up again after our September meetup to confirm.

**Comment by mrrrgn** [comment]
@aulvi Nice, thanks! One hitch, I was being too ambitious about October. I can't do September thanks to throat surgery (yuck), and my doc has warned me that I'll be super hoarse for six weeks or so. Probably need to do November instead if that's not a problem. Sorry!

**Comment by aulvi** [comment]
No problem, I'll bump this thread at the end of October and see how you're doing. I wish you an uneventful surgery and a speedy recovery. Looking forward to seeing your presentation when you're back at full strength, thanks again!

**Comment by obensource** [comment]
@FaustDeGoethe I just closed this issue, but did you in fact get the chance to give your talk? I may have been absent the night you did. If you'd still like to–we can definitely reopen this! :D
