### ISSUE TITLE
Talk Proposal: Sorting in Spidermonkey

### ISSUE THREAD

**Issue by mrrrgn** [PDXNode/pdxnode#75]
This year I was given the opportunity to implement `Array.sort` and `%TypedArray%.sort` in Firefox and Servo's JavaScript engine, Spidermonkey. The algorithms are humdrum, but the implementation details and challenges surrounding web compatibility turned out to yield some interesting lessons.

In this talk we will discuss the hows and whys surrounding SpiderMonkey's [five] sorting implementations along with a look at some fun bugs which arose due to subtle changes in sort behavior: for example, learning that some devs reverse arrays via `[...].sort(() => 1)` instead of `[...].reverse()`!

By the end of this talk JavaScript developers will have a better understanding of Spidermonkey's architecture and how they can take advantage of typed arrays and custom comparators to make their sorts run blazingly fast.

Estimated time: 45 minutes.

**Comment by mrrrgn** [comment]
This is the second proposal I've added. I don't mind to do either of the talks, or just shelve one of them in case you're in a pinch looking for speakers at some point down the line.

**Comment by bcomnes** [comment]
Wow super cool!

**Comment by mrrrgn** [comment]
Closing this for now. Will keep it in mind in case y'all need a speaker in the future.
