### ISSUE TITLE
Talk Proposal: Database Jones

### ISSUE THREAD

**Issue by jdduncan** [PDXNode/pdxnode#78]
I'd like to come talk about Database Jones, which is on github at github.com/mysql/mysql-js 

Jones is a framework for building database applications in node.js. It could work with any backend database. One of my hopes is that if I show people how efficient and usable the Jones front-end API is, they will want to chip in to create new connectors for their favorite databases. The currently supported databases are MySQL (using SQL) and MySQL Cluster (using NoSQL through the NDB API).

I could talk for 20 minutes, or 30, or 40.

**Comment by aulvi** [comment]
@jdduncan We would love to have you you present at our meetup, would you be available in January? As far as duration, 20-40 minutes  perfect, please let us know which you prefer and we'll get you on the calendar. Thanks!

**Comment by jdduncan** [comment]
Great, thank you!  January is good for me. 40 minutes is best, and 20 is really too short, and I could fit it in to 30 if needed.

**Comment by aulvi** [comment]
Awesome! 40 minutes is totally fine, I don't want you to feel too rushed :) I'll contact you again as we get closer to the date of the event. Thanks so much!

**Comment by jawa9000** [comment]
Can you provide a bullet list of talking points?

**Comment by jdduncan** [comment]
So is the date Jan 5th? Jan 12th?

**Comment by jdduncan** [comment]
@jawa9000 here is a bullet list:
  - Database Jones is a database access layer
  - It presents a thoroughly designed API
  - It can work with many databases, both SQL and NoSQL
  - It can work with the whole range of data models, from schemaless to fully relational
  - I'll describe the API and the architecture, and present a sample application

**Comment by jdduncan** [comment]
Also I'm wondering whether we will be at Urban Airship, or (as meetup says) at Vacasa.

**Comment by aulvi** [comment]
@jdduncan Sorry, been on vacation. Here's the skinny:

1. New venue, we're at Vacasa this month
2. New date, January 12th (second Thursday of the month)
3. Very excited to have you present!!

Please let me know if you have any questions, happy new year!

**Comment by jdduncan** [comment]
Hi Adam,

As long as the MAX orange line is running, I should be able to get there tomorrow.
