### ISSUE TITLE
🔒 add SSL

### ISSUE THREAD

**Issue by ungoldman** [PDXNode/pdxnode#81]
We should investigate adding SSL to the site so it works with the `https` protocol.

There are two fairly easy options I know of:

- (1) Fake SLL via Cloudflare (see [article](https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc))
- (2) Move our site to being hosted on a [DigitalOcean](https://www.digitalocean.com/) droplet

2 would require funds ($5/month), but would also provide us with free real SSL (easy to setup with https://letsencrypt.org), and give us the opportunity to deploy an actual node server and host other node projects on there too. There's also a good chance they might give us some free hosting as a sponsorship deal.

I'm partial to option 2, and if we end up going with that I'd be happy to document how I did it as a tutorial on how to get something like that set up.

**Comment by J2D2Development** [comment]
Another possible alternative might be Firebase hosting: https://firebase.google.com/products/hosting/

I've hosted a couple projects there and SSL is automatically configured.  Deploys are super easy, you can configure with a custom domain, and their free tier covers a good deal (I haven't had to pay for anything yet!).

The downside is that it's kind of a "backend as a service" model, so you don't really get to have much server-side fun.  However, if you're just looking for a simple hosting platform with built in SSL, I've found it pretty easy.

They do also have a "functions" feature that allows you to run Node type functions on their server (I think this is something like "serverless", but I'm a bit behind on my buzzwords!).  You can import npm pacakges and everything, so it's pretty cool.

Just another option for your consideration- thanks for putting together such a cool project!

**Comment by ungoldman** [comment]
Note: source for website moved to https://github.com/PDXNode/pdxnode.org

**Comment by ungoldman** [comment]
issue moved to pdxnode/pdxnode.org#4
