### ISSUE TITLE
Talk: Achieving npm dependency determinism, and why you want it

### ISSUE THREAD

**Issue by cdanielsen** [PDXNode/pdxnode#85]
**Who Am I**
I do software engineer in test work by day here in Portland. I have a dog named after Walter Cronkite. I love JS. Not sure what else should go here! =)

**What is your talk and/or demo about**
npm installs packages non-deterministically by default. This has benefits, but also non-trivial drawbacks as projects grow in size and complexity. In this talk, I'll discuss how to use some tooling and configuration to create an automated build system where a project's npm package tree can be maintained in a known state at all times, scanned for vulnerabilities, and upgraded over time with minimal overhead.

**The intended duration of your talk:**
15ish minutes

**Comment by obensource** [comment]
Hi @cdanielsen! My sincere apologies that we never responded to you about your talk request! If you're still interested in giving a talk we'd love to put you down for an upcoming presentation night! It doesn't have to be this same subject if you're more interested in something else now, but it definitely could be if you still want to give a talk on this!

Thanks a bunch, look forward to connecting with you and having you share an awesome talk with us!

**Comment by cdanielsen** [comment]
Hey @obensource, no worries... my schedule is not conducive to prepping for a talk atm anyway. Maybe will bring it back up at some point when things settle down a bit!
